import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class MyColors {
  MyColors();


  static const Color avalabilitycolor = Color(0xFFDBF1FF);
  static const Color viewcolor = Color(0xFFFF5A5F);
  static const Color primaryColor3 = Color(0xFF956EED);
  static const Color primaryColor2 = Color(0xFFA989F1);
  static const Color primery1 = Color(0xFFCEB9FF);
  static const Color red1 = Color(0xFFF50606);
  static const Color orange1 = Color(0xFFFFB800);
  static const Color whiteff = Color(0xFFFFFFFF);
  static const Color containerColor = Color(0xFFB5FB1E);
  static const Color backgroundcolor = Color(0xFFDADADA);
  static const Color padingcolors = Color(0xFFFF5740);
  static const Color starsColor = Color(0xFFB5FB1E);
  static const Color black1 = Color(0xFF222222);
  static const Color orange = Color(0xFFFF8C67);
  static const Color searchGrey = Color(0xFFF3F3F3);
  static const Color textFieldColor = Color(0xFFF9F4FF);
  static const Color primaryColor = Color(0xFF956EED);
  static const Color primaryDarkColor = Color(0xFF58488C);
  static const Color lightPrimaryColor = Color(0xFF823FE0);
  static const Color second = Color(0xFFECF0FF);
  static const Color blacka = Color(0xFF151515);
  static const Color appBackground = Color(0xFFF4F5FA);
  static const Color textColor = Color(0xFF094067);
  static const Color textField = Color(0xFFF9F4FF);
  static const Color socialBtn = Color(0xFFF9DBFF);
  static const Color welcomeBtn = Color(0xFFEFB9B6);
  static const Color termColor = Color(0xFFFFA370);

  static const Color white400 = Color(0xFFB1E0E6);
  static const Color white500 = Color(0xFFE5E4E2);
  static const Color darkBlue = Color(0xFF49A2DA);
  static const Color gradient1 = Color(0xFF9FC2F9);
  static const Color textPrivacy = Color(0xFF504545);
  static const Color hintText = Color(0xFF969696);
  static const Color textHeadLine = Color(0XFF1F1D1D);

  static const Color ratingColor = Color(0xFF6B7384);
  static const Color ratingColor2 = Color(0xFFE7EFFE);
  static const Color textColorLow = Color(0xFF525252);
  static const Color buttonColor = Color(0xFF4690FF);
  static const Color contain2 = Color(0xFFEDDEFE);
  static const Color contain3 = Color(0xFFC1EDEA);
  static const Color contain4 = Color(0xFFFFD4B0);
  static const Color blue15 = Color(0xFF49A2DA);
  static const Color blue50 = Color(0xFF2D9BF0);
  static const Color parpal = Color(0xFF414BB2);
  static const Color parpal10 = Color(0xFF695ACD);
  static const Color lightPink = Color(0xFFCB9AD3);
  static const Color cyned = Color(0xFF0CA789);
  static const Color blue10 = Color(0xFF2D9BF0);
  static const Color blue20 = Color(0xFFE8F1FF);
  static const Color white200 = Color(0xFFF1F8FF);
  static const Color lightBlue = Color(0xFF2babdd);
  static const Color yellow = Color(0xFFFFD54F);
  static const Color red500 = Color(0xfffc0000);
  static const Color grey = Color(0xff525252);
  static const Color grey72 = Color(0xFFC4C4C4);
  static const Color indigo200 = Color(0xFF9FA8DA);
  static const Color white = Color(0xFFFFFFFF);
  static const Color green50 = Color(0xFFE8F5E9);
  static const Color green100 = Color(0xFFB5FB1E);
  static const Color green200 = Color(0xFFA5D6A7);
  static const Color green300 = Color(0xFF81C784);
  static const Color green600 = Color(0xFF43A047);
  static const Color green700 = Color(0xFF388E3C);
  static const Color green800 = Color(0xFF2E7D32);
  static const Color black = Color(0xFF000000);
  static const Color black2 = Color(0xFF272727);
  static const Color black3 = Color(0xFF444444);
  static const Color grey100 = Color(0xFFF5F5F5);
  static const Color grey200 = Color(0xFFEEEEEE);
  static const Color fadedBlue = Color(0xFFE8F1FF);
  static const Color cardGrey = Color(0xFFE5E5E5);
  static const Color appbar = Color(0xFFECECEC);
  static const Color gray = Color(0xFF323F4B);
  static const Color yellow100 = Color(0xFFFFECB3);
  static const Color transparent = Color(0xFFF5F5F5);
  static const Color lightBlue1 = Color(0xFFBCE2FF);
  static const Color purple = Color(0xFF9E70EA);
  static const Color purple1 = Color(0xFFD159DB);
  static const Color teal = Color(0xFF489988);
  static const Color motion = Color(0xFF393346);
  static const Color lightPurple = Color(0xFFD9CEF3);
  static const Color lightTeal = Color(0xFF4AD6C8);
  static const Color lightBlue2 = Color(0xFF7685FC);
  static const Color facebook = Color(0xFF3B589C);
  static const Color google = Color(0xFFEC4235);
  static const Color tabbar = Color(0xFFF1F1F1);
  static const Color dialog = Color(0xFF5AAC63);
  static const Color splash = Color(0xFF1C2021);
  static const Color socialbtn = Color(0xFFE3E3E3);
  static const Color green = Color(0xFFB5FB1E);
  static const Color white900 = Color(0xFFF2F1F6);
  static const Color container1 = Color(0xFFE9FFE9);
  static const Color container2 = Color(0xFFF2EBFF);
  static const Color lightgreen = Color(0xFF86E487);
  static const Color white50 = Color(0xFFEDEDED);
  static const Color green10 = Color(0xFFD7FFD7);
}
